[WEB-966_WEB-874]  osmosis swap 적용 & cosmos 사인 시 메세지 갯수에 따라 메세지창 크기 변경
cosmostation/cosmostation-chrome-extension pull request #135
Opened 2023-01-26 06:59 UTC by G-Gamja

## 오스모시스 스왑
익스텐션에서 오스모시스 디파이 기능을 사용할 수 있도록 스왑 페이지 및 관련 기능들을 추가했습니다.

- 교환 비율 , price impact등의 계산 수식은 osmosis-frontend에서 사용한 수식을 참고하여 작성했습니다.
- 교환 가능한 코인의 리스트는 chainlist/osmosis/pool.json 에서 가져오고 있습니다.

![스크린샷 2023-01-26 오후 3 47 21](https://user-images.githubusercontent.com/87967564/214774389-7bdee1ba-b2b8-4b96-aebe-c2cda5ea22ae.png)
![스크린샷 2023-01-26 오후 3 47 10](https://user-images.githubusercontent.com/87967564/214774398-044f6e8c-d60f-4bb4-bf6e-6696cbcdac72.png)

- 코인 구매 버튼은 우선 비활성화했습니다.
- 번역어를 수정해야할 가능성이 있습니다.

## cosmos 사인 시 메세지 갯수에 따라 메세지창 크기 변경 & 상단 부분 고정화

메시지의 갯수에 따라 메세지 창의 높이를 동적으로 변경되도록 분기처리 했습니다. 또 상단의 텍스트 영역은 overflow시에도 고정되도록 코드를 변경했습니다.
- 다이렉트 형식의 요청을 위한 바닐라 코드는 지라 티켓 댓글에 정리했습니다.
- https://cosmostation.atlassian.net/browse/WEB-874?atlOrigin=eyJpIjoiZWRkMTkwNGViNWMxNGQ3YzhhN2M5ODViNDMwYjEyMWEiLCJwIjoiaiJ9

![스크린샷 2023-01-26 오후 3 56 59](https://user-images.githubusercontent.com/87967564/214775305-092b951b-3dc1-4984-8c8f-0dddb403c774.png)

![스크린샷 2023-01-26 오후 3 59 03](https://user-images.githubusercontent.com/87967564/214775517-97898d8c-19de-4204-a676-a1cdfd21d2bc.png)

2023-02-02 02:19 UTC, ong-ar requested changes

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/components/CoinAmountInfoContainer/styled.tsx
> +  justifyContent: 'flex-start',
`flex-start` 를 따로 넣어준 이유가 있을까요?

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +  const currentChainAssets = useAssetsSWR(OSMOSIS);
상위 컴포넌트에서 chain 받아서 처리하시면 될 것 같습니다.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/components/CoinAmountInfoContainer/index.tsx
> +          <Tooltip title={displayDenom || 'Unknown'} arrow placement="top">
`{displayDenom || 'Unknown'}` 변수로 빼주세요.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +                {inputCoinAmountPrice === '0' ? (
price 는 unknown 보다는 0 그대로 노출하는게 좋을 것 같습니다.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +                {outputCoinAmountPrice === '0' ? (
여기도 0 그대로 노출해주세요.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +            {routesTokenOutDisplayDenomList.map((item) => (
string 으로 만든 다음에 typography 에 넣는 방법이 좋을 것 같습니다.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +            {routes.map((item, index) => (
string 으로 만든 다음에 typography 에 넣는 방법이 좋을 것 같습니다.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/components/CoinListBottomSheet/index.tsx
> +  const [debouncedSearch] = useDebounce(search, 500);
통신이 따로 없으면 debounce 안걸어도 될 것 같습니다.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/components/CoinListBottomSheet/index.tsx
> +  const filteredCoinList = debouncedSearch
useMemo 추가해주세요.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/components/SlippageSettingDialog/index.tsx
> +  const [slippage, setCurrentSlippage] = useState(currentSlippage);
state 변수 하나면 될 것 같습니다.

2023-02-02 02:19 UTC, ong-ar commented on src/Popup/pages/Wallet/components/cosmos/NativeChainCard/styled.tsx
> +    backgroundColor: theme.accentColors.purple02,
`cursor: pointer` 하나 추가해주세여

2023-02-02 02:19 UTC, ong-ar commented on src/types/cosmos/pool.ts
> +export type WeightedPoolResponse = {
`WeightedPoolResponse`, `StablePoolResponse`

삭제 하고 `PoolResponse` 만 만들어서 사용하면 좋을 것 같습니다.

```
export type PoolResponse = {
  pool: WeightedPool | StablePool
};
```

2023-02-02 02:19 UTC, ong-ar commented on src/types/cosmos/swap.ts
> +export type SwapAmountInRoute = {
파일 이름을 osmosisSwap 또는 type 이름에 osmosis 를 추가해주세요.

2023-02-02 02:28 UTC, ong-ar requested changes

2023-02-02 02:28 UTC, ong-ar commented on src/Popup/hooks/SWR/cosmos/usePoolsSWR.ts
> +export type PoolResponse = WeightedPoolResponse | StablePoolResponse;
제거하고 type 파일에서 합쳐주세요.

2023-02-02 02:28 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +  const address = accounts.data?.find((item) => item.id === currentAccount.id)?.address[chain.id] || '';
useMemo 추가해주세요

2023-02-02 02:28 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +  const poolDenomList = poolsAssetData.data ? [...poolsAssetData.data.map((item) => item.adenom), ...poolsAssetData.data.map((item) => item.bdenom)] : [];
useMemo 추가해주세요.

2023-02-02 02:28 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +  useEffect(() => {
`useEffect` 는 될 수 있으면 제일 아래로 이동시켜주세요.

2023-02-02 02:28 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +    }
output 이 0 일 때도 추가해주세요.

2023-02-02 02:28 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +          chainName: convertAssetNameToCosmos(item.prevChain || item.origin_chain)?.chainName || getCapitalize(item.prevChain || item.origin_chain),
prevChain 으로 쓰기로 하지 않았나요? 뭔가 길어진 느낌인데

2023-02-02 02:54 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/components/CoinAmountInfoContainer/styled.tsx
> +  justifyContent: 'flex-start',
컴포넌트로 리팩토링하면서 불필요한 코드가 남은것 같습니다. 삭제하겠습니다.

2023-02-02 02:55 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +  const currentChainAssets = useAssetsSWR(OSMOSIS);
수정하겠습니다

2023-02-02 03:01 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/components/CoinAmountInfoContainer/index.tsx
> +          <Tooltip title={displayDenom || 'Unknown'} arrow placement="top">
수정했습니다

2023-02-02 03:03 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +                {inputCoinAmountPrice === '0' ? (
수정했습니다

2023-02-02 03:03 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +                {outputCoinAmountPrice === '0' ? (
수정했습니다

2023-02-02 04:41 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +            {routesTokenOutDisplayDenomList.map((item) => (
수정했습니다

2023-02-02 04:41 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Swap/index.tsx
> +            {routes.map((item, index) => (
위와 동일한 방식으로 수정했습니다

2023-02-02 04:45 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/components/CoinListBottomSheet/index.tsx
> +  const [debouncedSearch] = useDebounce(search, 500);
수정했습니다

2023-02-02 04:45 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/components/CoinListBottomSheet/index.tsx
> +  const filteredCoinList = debouncedSearch
수정했습니다

2023-02-02 05:02 UTC, G-Gamja commented on src/Popup/pages/Wallet/components/cosmos/NativeChainCard/styled.tsx
> +    backgroundColor: theme.accentColors.purple02,
수정했습니다

2023-02-02 05:04 UTC, G-Gamja commented on src/types/cosmos/pool.ts
> +export type WeightedPoolResponse = {
수정했습니다

2023-02-02 05:13 UTC, G-Gamja commented on src/Popup/hooks/SWR/cosmos/usePoolsSWR.ts
> +export type PoolResponse = WeightedPoolResponse | StablePoolResponse;
수정했습니다

2023-02-02 05:15 UTC, G-Gamja commented on src/types/cosmos/swap.ts
> +export type SwapAmountInRoute = {
수정했습니다

2023-02-02 05:16 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +  const address = accounts.data?.find((item) => item.id === currentAccount.id)?.address[chain.id] || '';
수정했습니다

2023-02-02 05:17 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +  const poolDenomList = poolsAssetData.data ? [...poolsAssetData.data.map((item) => item.adenom), ...poolsAssetData.data.map((item) => item.bdenom)] : [];
수정했습니다

2023-02-02 05:19 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +  useEffect(() => {
수정했습니다

2023-02-02 05:21 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +    }
수정했습니다

2023-02-02 05:26 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +          chainName: convertAssetNameToCosmos(item.prevChain || item.origin_chain)?.chainName || getCapitalize(item.prevChain || item.origin_chain),
다시보니 `convertAssetNameToCosmos` 메서드는 굳이 안써도 됐을 것 같습니다. 수정했습니다

2023-02-02 08:13 UTC, G-Gamja commented on src/Popup/pages/Wallet/Swap/components/SlippageSettingDialog/index.tsx
> +  const [slippage, setCurrentSlippage] = useState(currentSlippage);
커스텀 인풋을 감싸는 컨테이너에 커스텀 입력값여부를 props로 전달하기 위해 슬리피지 상태변수를 2개로 두었습니다.
커스텀 슬리피지 상태변수를 지우면 단순 버튼 입력과 커스텀 슬리피지 입력을 구분하기 어려워질 것 같습니다.

2023-02-02 10:22 UTC, G-Gamja commented
@ong-ar  인석님 tx message 헤더 부분 고정하는 코드가 코스모스 계열만 작성했는데 다른 이더리움이나 앱토스에도 적용시켜야할까요?

2023-02-23 01:59 UTC, ong-ar approved these changes
고생하셨습니다.

2023-02-23 01:59 UTC, ong-ar commented on src/Popup/hooks/SWR/cosmos/usePoolsSWR.ts
> +export function usePoolSWR(poolId?: string, config?: SWRConfiguration) {
usePoolSWR 파일 이름이랑 맞춰주세요.

2023-02-23 01:59 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +      ...swapCoinList.filter((item) => gt(item?.availableAmount || 0, 0) && (item.type === 'staking' || item.type === 'native')),
bridge

2023-02-23 01:59 UTC, merged