[WEB-1315] 내 주소 버튼 hover사이즈 줄이기 & 모든 체인에 내 주소 버튼 추가 & Sui send페이지 오류수정
cosmostation/cosmostation-chrome-extension pull request #137
Opened 2023-02-01 06:25 UTC by G-Gamja

- 내 전체 계정, 주소록을 볼 수 있는 버튼의 hover, active 사이즈를 줄였습니다.

![스크린샷 2023-02-01 오후 3 22 31](https://user-images.githubusercontent.com/87967564/215967513-d8a5dfaf-3176-4f9a-ac67-bb58d3f56475.png)

- 이더리움, 앱토스, 수이 체인에서 send시 전체 계정, 주소록을 확인할 수 있는 버튼을 추가했습니다.

![스크린샷 2023-02-01 오후 3 24 44](https://user-images.githubusercontent.com/87967564/215967576-2eda3ad9-88c9-4161-8a5e-a7ae40358f16.png)

2023-02-02 02:37 UTC, ong-ar requested changes

2023-02-02 02:37 UTC, ong-ar commented on src/Popup/components/AccountAddressBookBottomSheet/index.tsx
> +  token?: EthereumNetwork;
이건 체인 이미지로만 가도 괜찮을 것 같습니다. token 삭제해주세요.

2023-02-02 10:16 UTC, G-Gamja commented on src/Popup/components/AccountAddressBookBottomSheet/index.tsx
> +  token?: EthereumNetwork;
수정했습니다

2023-02-03 02:45 UTC, ong-ar approved these changes
고생하셨습니다.

2023-02-06 06:19 UTC, merged