[Extension] Withdraw Commission 기능 추가
cosmostation/cosmostation-chrome-extension pull request #147
Opened 2023-03-02 06:10 UTC by G-Gamja

tx 시뮬레이션 로직을 활용하여 커미션 tx 생성시 예상되는 수수료를 사용하여 커미션을 받을 수 있는 기능을 추가했습니다.

- 검증인 주소 fetching 및 캐싱에 성공했다면 다시 가져오지 않습니다

<img width="458" alt="스크린샷 2023-03-02 오후 2 59 31" src="https://user-images.githubusercontent.com/87967564/222345054-11c316d0-293d-4e16-99bd-49acab1235b0.png">
<img width="446" alt="스크린샷 2023-03-02 오후 2 59 07" src="https://user-images.githubusercontent.com/87967564/222345058-549d199b-1c07-418c-a208-421849cc2714.png">

2023-03-05 07:31 UTC, ong-ar requested changes
https://github.com/cosmostation/cosmostation-chrome-extension/pull/147/commits/4b55e8068e690e6b46dd0f189f94db3a78c56a12

https://github.com/cosmostation/cosmostation-chrome-extension/pull/147/commits/680c3956a922459c9b5b5772da3fa9cb61dc866b

커밋 추가했습니다.

컴포넌트가 중복되는 것 같아서 변경하였고, useMemo 추가 그리고 skeleton 및 노출 변경했습니다.

관련해서 확인하시고 툴팁 추가까지만하면 문제 없을 것 같습니다.

작업은 월요일에 해주시고 다시 한번 요청주세요.

2023-03-05 07:31 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Commission/index.tsx
> +            <Typography variant="h5">{shorterAddress(msg.value.validator_address, 32)}</Typography>
`validator_address` 툴팁 추가 해주세요.

2023-03-06 01:16 UTC, G-Gamja commented
> [4b55e80](https://github.com/cosmostation/cosmostation-chrome-extension/commit/4b55e8068e690e6b46dd0f189f94db3a78c56a12)
> 
> [680c395](https://github.com/cosmostation/cosmostation-chrome-extension/commit/680c3956a922459c9b5b5772da3fa9cb61dc866b)
> 
> 커밋 추가했습니다.
> 
> 컴포넌트가 중복되는 것 같아서 변경하였고, useMemo 추가 그리고 skeleton 및 노출 조건 변경했습니다.
> 
> 관련해서 확인하시고 툴팁 추가까지만하면 문제 없을 것 같습니다.
> 
> 작업은 월요일에 해주시고 다시 한번 요청주세요.

넵 알겠습니다

2023-03-06 01:23 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Amino/components/TxMessage/messages/Commission/index.tsx
> +            <Typography variant="h5">{shorterAddress(msg.value.validator_address, 32)}</Typography>
추가했습니다

2023-03-06 02:04 UTC, ong-ar approved these changes
고생하셨습니다.

2023-03-06 02:04 UTC, merged