[Extension] Change sign mode to Direct in Claim Commission tx on Evmos(cosmos)
cosmostation/cosmostation-chrome-extension pull request #149
Opened 2023-03-07 03:24 UTC by G-Gamja

기존 커미션을 받는 tx의 레거시 아미노 사인 방식에서 Evmos에서만 direct방식으로 변경하였습니다.
- 인앱에서 다이렉트 사인 메시지를 처리할 수 있는 분기처리 코드가 추가되었습니다.
- evmos에서만 다이렉트 방식으로 사인을 합니다. 그 외 체인에서는 모두 레거시 아미노 방식으로 사인을 합니다.

<img width="435" alt="스크린샷 2023-03-07 오후 12 16 14" src="https://user-images.githubusercontent.com/87967564/223311493-d8afaa4a-27c2-42c8-a02f-9339f05acb34.png">
<img width="447" alt="스크린샷 2023-03-07 오후 12 16 02" src="https://user-images.githubusercontent.com/87967564/223311504-aab7ca06-5ec0-4530-923a-d1aedb97273f.png">
<img width="428" alt="스크린샷 2023-03-07 오후 12 15 52" src="https://user-images.githubusercontent.com/87967564/223311508-5f9a38c6-0604-4fee-bea5-734ed67134f2.png">

2023-03-07 03:43 UTC, wannabit-yongjoo commented
🤸‍♂️

2023-03-16 02:31 UTC, ong-ar requested changes
수정하고 다시 말씀주세요.

2023-03-16 02:31 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Direct/entry.tsx
> +                      const publicKeyType = PUBLIC_KEY_TYPE.SECP256K1;
이거 type 한번 가져올 수 있도록 처리해주세요.
`getPublicKeyType`

2023-03-16 02:31 UTC, ong-ar commented on src/Popup/pages/Wallet/components/cosmos/NativeChainCard/index.tsx
> +      commissionDirectTx
evmos

2023-03-16 02:53 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Direct/entry.tsx
> +                      const publicKeyType = PUBLIC_KEY_TYPE.SECP256K1;
수정했습니다

2023-03-16 02:53 UTC, G-Gamja commented on src/Popup/pages/Wallet/components/cosmos/NativeChainCard/index.tsx
> +      commissionDirectTx
수정했습니다

2023-03-16 03:11 UTC, ong-ar approved these changes
고생하셨습니다.

2023-03-16 03:11 UTC, merged