[WEB-1420] 통합 스왑 구현
cosmostation/cosmostation-chrome-extension pull request #165
Opened 2023-04-05 07:17 UTC by G-Gamja

Squid swap api, 1inch swap api, Osmo swap을 하나의 페이지로 통합하여 통합 스왑 페이지를 구현했습니다.

### 체인 선택에 따라 사용할 스왑 api가 결정됩니다.
- 송, 수신 체인이 선택되면 사용할 api가 결정됩니다.
  - 송, 수신 체인이 Osmosis이면 Osmosis Swap을 사용합니다.
  - 송, 수신 체인이 EVM계열이며 같은 체인이라면 1inch Swap을 사용합니다.
  - 송, 수신 체인이 EVM계열이며 서로 다른 체인이거나, 송신 체인이 EVM이며 수신 체인이 Cosmos계열이라면 Squid Swap을 사용합니다.
  
- 체인이 선택되기 전까지는 토큰을 선택할 수 없습니다.

#### 스왑 페이지 라우팅
- 어떤 체인에서 스왑 페이지로 이동하느냐에 따라 송신체인이 자동 선택됩니다.
  - e.g 이더리움 체인에서 스왑 페이지로 이동 시 송신 체인이 이더리움으로 자동 선택됩니다.
  - 송신 체인 목록에 없는 체인에서 스왑 페이지로 이동 시에는 아무 체인도 선택되지 않은 상태로 이동합니다.

#### 체인 리스팅
- 송, 수신 어떤 체인을 선택하느냐에 따라 선택 가능한 Opposite 체인의 리스팅이 영향을 받습니다. 따라서 송, 수신 체인의 선 선택을 플래그로 설정하여 체인 선택 영향의 방향을 고정시켰습니다. 

#### 토큰 리스팅
- 몇몇 케이스에서 데이터 로딩에 지나치게 오랜 시간이 걸려 splice후 Intersection observer를 사용하여 스크롤할 수록 보여지는 토큰의 수를 늘렸습니다.

#### 1inch 스왑 시 특이점
- 1inch `Swap` api에서는 토큰의 price정보를 주지 않습니다. 이를 위해서는 spotPriceAggregator를 사용해서 가격 정보를 얻어야합니다.
  - 따라서 가격 정보를 노출시키지 않고 있으며, Native 코인만 Tx fee cost 노출을 위해 익스텐션 내에서 사용하는 코인 게코를 통해 가격 정보를 보여주고 있습니다.
  - 가격 정보가 없기에 price impact정보를 제거했습니다 
- 1inch 스왑에서 사용하는 스마트 컨트랙은 스왑할 토큰에 접근할 권한을 취득해야합니다. 따라서 스왑을 원하는 토큰이 1inch 컨트렉에 allowance가 설정되어 있지 않다면 이를 허락해주는 tx를 1번 post해야합니다.
  - 이때 설정되는 allowance의 정도는 최대 한도로 설정되어 있습니다.
  - allowance tx 사인 시에는 사인 후에 Swap 페이지로 라우팅 됩니다. 
- 1inch 스왑 사인 후에는 To Token을 커스텀 토큰으로 자동으로 추가하고 있습니다. 코인 게코 아이디는 1inch api에서 제공하지 않아 이는 포함하지 않고 있습니다.
- 현재는 `referrerAddress`를 할당하지 않고 있습니다. 추후 추천인 주소, fee 비율을 설정할 수 있습니다.
- 1inch Docs에서 api를 사용하여 나온 gaslimit를 그대로 사용하는 것을 추천하지 않고 있습니다. 따라서 디폴트 가스 배율을 적용시키고 있습니다.

#### Squid swap 시 특이점
- Swap tx를 post후 fee가 spike되는 경우 swap과정이 멈출 수 있습니다. 이러한 경우 axelar scan에서 직접 fee를 추가로 지불하거나, squid sdk에서 제공하는 fee추가 지불 메서드를 사용해야 합니다. 추후 구현될 activity페이지에서 구현될 가능성이 있습니다.

- 1inch 스왑 페이지
<img width="453" alt="스크린샷 2023-04-05 오후 4 38 47" src="https://user-images.githubusercontent.com/87967564/230013683-fcd85579-33f0-4e23-bce6-08ea741a44d5.png">
- squid 스왑 페이지
<img width="457" alt="스크린샷 2023-04-05 오후 4 40 07" src="https://user-images.githubusercontent.com/87967564/230015310-e45a52c6-3db5-402a-ac7f-ae55d625b444.png">
- osmo 스왑 페이지
<img width="444" alt="스크린샷 2023-04-05 오후 4 51 37" src="https://user-images.githubusercontent.com/87967564/230016569-5f987202-58a2-4da1-b601-f6e0affbe77c.png">

그 외
- Osmo, 1inch Swap시 볼 수 있는 Tx cost는 버튼으로 만들어 currecy, fee token amount 두 값을 변경하며 확인해 보실 수 있습니다.
- api마다 제공할 수 있는 정보가 달라 Swap Info를 각각에 알맞는 정보들을 선택적으로 노출시켰습니다.
<img width="405" alt="스크린샷 2023-04-05 오후 4 38 10" src="https://user-images.githubusercontent.com/87967564/230013545-fe1ec802-6b1d-4c4d-8998-6e2266992e73.png">
<img width="394" alt="스크린샷 2023-04-05 오후 4 38 14" src="https://user-images.githubusercontent.com/87967564/230013552-b95a8a5b-0e4c-45f0-8714-367ea651c6ee.png">

2023-04-10 07:35 UTC, ong-ar requested changes
볼게 너무 많아서 내일 한번 같이 보시죠

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/pages/Wallet/OsmosisSwap/components/SlippageSettingDialog/index.tsx
> +  const [customSlippage, setCustomSlippage] = useState('');
state 하나로 가능할 것 같습니다.

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/SWR/1inch/useAllowanceTxSWR.ts
> +  const requestURL = allowanceTxParam && `${ONEINCH_BASE_URL}${allowanceTxParam.chainId}/approve/transaction?tokenAddress=${allowanceTxParam.tokenAddress}`;
`ONEINCH_BASE_URL` 마지막 `/` 지우고 `${ONEINCH_BASE_URL}/${allowanceTxParam.chainId}/approve/transaction?` 으로 변경해주세요.

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/SWR/cosmos/useBalanceSWR.ts
> +  const address = (chain && accounts.data?.find((account) => account.id === chromeStorage.selectedAccountId)?.address[chain?.id]) || '';
요거 한번 정리 해야 할 것 같네요.
chain 이 없을 때 따로 처리하는 게 좋을 것 같습니다.

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/SWR/1inch/useTokenBalanceSWR.ts
> +export function useTokenBalanceSWR(currentEthereumNetwork?: IntegratedSwapEVMChain, token?: IntegratedSwapToken, config?: SWRConfiguration) {
이것도 기존거 같이 사용할 수 있을 것 같네요.

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/SWR/squid/useSquidSDKSWR.ts
> +export function useSquidSDKSWR(config?: SWRConfiguration) {
`useSquidSDKSWR` -> `useSquidSWR` 가 나을 것 같습니다.

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/SWR/squid/useSquidRouteSWR.ts
> +    await squid.init();
이것도 같이 쓸 수 있을 것 같네요.

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/SWR/squid/useSquidTxStatusSWR.ts
> +    await squid.init();
`useSquidSDKSWR` 를 이용해서 같이 사용할 수 있을 것 같네요

2023-04-10 07:35 UTC, ong-ar commented on src/Popup/hooks/osmoSwap/SWR/usePoolsSWR.ts
> +  const requestURL = poolId && `https://lcd-osmosis-app.cosmostation.io/osmosis/gamm/v1beta1/pools/${poolId}`;
이건 왜 바꾼겁니까?

2023-04-10 07:37 UTC, G-Gamja commented
> 볼게 너무 많아서 내일 한번 같이 보시죠

넵 알겠습니다

2023-04-11 06:58 UTC, ong-ar commented on src/Popup/hooks/useCurrent/useCurrentQueue.ts
> +  const backDeQueue = async () => {
중복 코드 제거

2023-04-11 07:03 UTC, ong-ar commented on src/Popup/pages/Account/Management/entry.tsx
> +      <SubSideHeader title={t('pages.Account.Management.layout.title')}>
다시 살려주세요.

2023-04-11 07:11 UTC, ong-ar commented on src/Popup/pages/Popup/Ethereum/Transaction/entry.tsx
> +  const provider = new Web3.providers.HttpProvider(currentEthereumNetwork.rpcURL, {
전체적으로 다시 determineTxType 을 이용해서 abi 풀어서 해보세요.

2023-04-19 08:12 UTC, ong-ar commented on src/Popup/pages/Wallet/components/cosmos/NativeChainCard/index.tsx
> +          <IconButtonContainer sx={{ display: 'none' }}>
안쓸거 같으면 아예 지워주세요

2023-04-25 03:24 UTC, ong-ar commented on src/Popup/pages/Popup/Ethereum/Transaction/entry.tsx
> +                        if (queue.channel === 'inApp' && txType.data?.type === 'approve') {
erc20 특정 시켜주세요.

2023-04-25 03:29 UTC, ong-ar commented on src/constants/route.ts
> +  WALLET__OSMOSIS_SWAP: '/wallet/osmosisSwap',
`osmosisSwap` -> `osmosis-swap` 변경해주세요.

2023-04-26 01:33 UTC, G-Gamja commented on src/Popup/pages/Wallet/OsmosisSwap/components/SlippageSettingDialog/index.tsx
> +  const [customSlippage, setCustomSlippage] = useState('');
커스텀입력과 프리셋 버튼과의 입력의 상태 차이를 두고자 기존과 같이 구현했습니다.

2023-04-26 01:34 UTC, G-Gamja commented on src/Popup/hooks/SWR/1inch/useAllowanceTxSWR.ts
> +  const requestURL = allowanceTxParam && `${ONEINCH_BASE_URL}${allowanceTxParam.chainId}/approve/transaction?tokenAddress=${allowanceTxParam.tokenAddress}`;
수정했습니다

2023-04-26 01:35 UTC, G-Gamja commented on src/Popup/hooks/SWR/1inch/useTokenBalanceSWR.ts
> +export function useTokenBalanceSWR(currentEthereumNetwork?: IntegratedSwapEVMChain, token?: IntegratedSwapToken, config?: SWRConfiguration) {
해당 메서드는 삭제한 후 기존 이더리움 토큰 밸런스를 가져오는 메서드에 입력 파라미터를 추가하는 방식으로 수정했습니다.

2023-04-26 01:35 UTC, G-Gamja commented on src/Popup/hooks/SWR/squid/useSquidSDKSWR.ts
> +export function useSquidSDKSWR(config?: SWRConfiguration) {
수정했습니다

2023-04-26 01:35 UTC, G-Gamja commented on src/Popup/hooks/SWR/squid/useSquidRouteSWR.ts
> +    await squid.init();
수정했습니다

2023-04-26 01:35 UTC, G-Gamja commented on src/Popup/hooks/SWR/squid/useSquidTxStatusSWR.ts
> +    await squid.init();
수정했습니다

2023-04-26 01:36 UTC, G-Gamja commented on src/Popup/hooks/osmoSwap/SWR/usePoolsSWR.ts
> +  const requestURL = poolId && `https://lcd-osmosis-app.cosmostation.io/osmosis/gamm/v1beta1/pools/${poolId}`;
코드 가독성이 좋아보일 것이라 생각했는데 리턴 타입이 2개가 되는 상황을 예상하지 못했습니다. 기존 코드로 다시 수정했습니다

2023-04-26 01:37 UTC, G-Gamja commented on src/Popup/hooks/useCurrent/useCurrentQueue.ts
> +  const backDeQueue = async () => {
해당 메서드 삭제한 후에 기존 메서드에 path 파라미터를 옵셔널로 받을 수 있도록 수정했습니다

2023-04-26 01:37 UTC, G-Gamja commented on src/Popup/pages/Account/Management/entry.tsx
> +      <SubSideHeader title={t('pages.Account.Management.layout.title')}>
수정했습니다

2023-04-26 01:38 UTC, G-Gamja commented on src/Popup/pages/Popup/Ethereum/Transaction/entry.tsx
> +  const provider = new Web3.providers.HttpProvider(currentEthereumNetwork.rpcURL, {
kind타입을 추가하여 메서드를 수정하여 determinTxType으로 erc20과 swap(1inch)를 구분할 수 있도록 수정했습니다.

2023-04-26 01:38 UTC, G-Gamja commented on src/Popup/pages/Wallet/components/cosmos/NativeChainCard/index.tsx
> +          <IconButtonContainer sx={{ display: 'none' }}>
수정했습니다

2023-04-26 01:39 UTC, G-Gamja commented on src/constants/route.ts
> +  WALLET__OSMOSIS_SWAP: '/wallet/osmosisSwap',
수정했습니다

2023-04-26 08:24 UTC, G-Gamja commented on src/Popup/pages/Popup/Ethereum/Transaction/entry.tsx
> +                        if (queue.channel === 'inApp' && txType.data?.type === 'approve') {
수정은 완료했습니다. 현재 1inch api사용이 블락되어서 테스트를 못하고 있습니다. 테스트 후에 리졸브하겠습니다.

2023-05-04 02:52 UTC, ong-ar commented on src/Popup/pages/Wallet/Swap/entry.tsx
> +    if (currentSwapAPI === 'squid' && currentToChain?.line === ethereumChain.line) {
`ethereumChain.line` -> `ETHEREUM`

2023-05-16 06:46 UTC, ong-ar approved these changes
고생하셨습니다.

2023-05-16 06:47 UTC, merged