[APIS-272] 1inch spot price api 추가
cosmostation/cosmostation-chrome-extension pull request #326
Opened 2024-04-29 08:38 UTC by G-Gamja

1inch spot price api를 추가하여 1inch 스왑 시 사전에 코인 게코 id값이 설정되어 있는 '추가된'토큰을 제외한 토큰에서도 가격을 확인할 수 있도록 했습니다.

- 일부 currency는 1inch spot api에서 지원하지 않아 가격을 0으로 표시합니다.
  - BTC, ETH

![스크린샷 2024-04-29 오후 5 23 11](https://github.com/cosmostation/cosmostation-chrome-extension/assets/87967564/d9e0457d-f2eb-49d8-a046-56e89d536851)

2024-05-08 09:01 UTC, G-Gamja commented
QA 통과했습니다.

@ong-ar

2024-05-09 09:43 UTC, ong-ar commented on src/Popup/hooks/SWR/integratedSwap/oneInch/SWR/useOneInchTokensSWR.ts
> +    isPaused: () => !parsedChainId,
요거 suspense 쓸 때 영향도가 있는데 아직 쓰는데가 없는 것 같아서 우선 approve 할게요.

2024-05-09 09:45 UTC, ong-ar commented on src/Popup/utils/string.ts
> +export function fromHex(hex?: string) {
hexToDecimal 이 좋을 거 같습니다.

2024-05-09 09:46 UTC, ong-ar requested changes
@G-Gamja 

함수 이름 하나 변경 부탁드립니다.

fromhex 라고 할려면 to 로 여러가지로 나온다면 파라미터로 결과 값 형식도 받으면 좋을 것 같네요.

2024-05-09 10:24 UTC, G-Gamja commented on src/Popup/hooks/SWR/integratedSwap/oneInch/SWR/useOneInchTokensSWR.ts
> +    isPaused: () => !parsedChainId,
넵 알겠습니다.

2024-05-09 10:25 UTC, G-Gamja commented on src/Popup/utils/string.ts
> +export function fromHex(hex?: string) {
넵, 함수명을 변경하는 방향으로 수정하겠습니다.

2024-05-09 10:28 UTC, G-Gamja commented
> @G-Gamja
> 
> 함수 이름 하나 변경 부탁드립니다.
> 
> fromhex 라고 할려면 to 로 여러가지로 나온다면 파라미터로 결과 값 형식도 받으면 좋을 것 같네요.

함수명을 수정해서 푸시했습니다. 확인 부탁드립니다.
- fromHex -> hexToDecimal

2024-05-10 02:55 UTC, ong-ar approved these changes
고생하셨습니다.

2024-05-10 02:56 UTC, merged