[APSI-327] Support enable api
cosmostation/cosmostation-chrome-extension pull request #341
Opened 2024-05-28 03:35 UTC by G-Gamja

Keplr 인터페이스의 enable api를 지원하는 코드를 추가했습니다.
- 파라미터에 지원하지 않는 체인이 포함될 경우, 지원하지 않는 체인들 중 가장 낮은 인덱스의 값만 에러로 리턴합니다.

2024-05-28 05:07 UTC, ong-ar requested changes

2024-05-28 05:07 UTC, ong-ar commented on src/Scripts/injectScript/cosmos.ts
> +const enable: Keplr['enable'] = async (chainIds: string[] | string) => {
chainIds 가 없을 때도 처리 부탁드려요

`chain id not set`

2024-05-28 05:15 UTC, G-Gamja commented on src/Scripts/injectScript/cosmos.ts
> +const enable: Keplr['enable'] = async (chainIds: string[] | string) => {
수정했습니다. 확인 부탁드립니다.

2024-05-28 08:14 UTC, ong-ar approved these changes
고생하셨습니다.

2024-05-29 07:24 UTC, G-Gamja commented
QA 통과했습니다.

2024-05-30 02:12 UTC, merged