[APIS-353] Refactor 'signature' field to 'signatures' in ProtoTxBytesProps
cosmostation/cosmostation-chrome-extension pull request #356
Opened 2024-06-27 08:14 UTC by G-Gamja

멀티시그 트랜잭션을 Direct sign하는 과정에서 생기던 가스 시뮬레이션 오류를 해결했습니다.

- Direct Sign페이지에서 가 이제 `signer_infos`의 길이에 따라 다중 서명을 지원합니다. 이전에는 단일 서명만을 사용했습니다.
  - 기존에는 `signer_infos`의 길이와 상관없이 단일 시그니처 스트링만 아규먼트로 사용합니다.
- protoTxBytes 함수에서 다중 서명 지원 추가
  - `protoTxBytes`의 `signature` 매개변수가 `signatures`로 변경되었습니다.(string -> string[])
  - `signatures` 배열은 각 서명을 base64에서 Buffer로 변환되어 매핑됩니다.
- 해당 작업으로 authz grant msg를 비롯 signer_infos에 2개 이상의 pub key가 포함된 tx의 시뮬레이션 오류를 해결합니다.

2024-07-11 03:16 UTC, ong-ar commented on src/Popup/pages/Popup/Cosmos/Sign/Message/entry.tsx
>                      const pTx = protoTx(tx, base64Signature, pubKey);
protoTx 를 변경하는 건 어떨까 싶습니다.

입력값 그대로 리턴하는데.... 음... 아예 빼도 괜찮을 것 같기도 하고 의견 한번 부탁드립니다.

2024-07-11 03:19 UTC, ong-ar requested changes
protoTx
protoTxBytes

두개를 맞추거나 protoTx 에서 signature 를 제외하고 따로 관리하는 방법으로 한번 수정해주세요.

2024-07-11 03:35 UTC, G-Gamja commented on src/Popup/pages/Popup/Cosmos/Sign/Message/entry.tsx
>                      const pTx = protoTx(tx, base64Signature, pubKey);
protoTx의 파라미터의 타입 중 `signature: string`을 `signatures:string[]`으로 변경하여
pTx값을 스프레드한 값을 protoTx함수의 아규먼트로 사용될 수 있도록 수정하겠습니다.

2024-07-12 04:14 UTC, G-Gamja commented
QA가 필요한 작업입니다.

2024-07-15 03:29 UTC, ong-ar approved these changes
고생하셨습니다.

2024-07-15 10:19 UTC, G-Gamja commented
QA 통과되었습니다.

2024-07-16 02:36 UTC, merged